# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cxx_convert_maf_to_fasta <- function(maf_file, species_file, chrom_size_file, output_folder, reference_species = "", buffer_limit_mb = 100L) {
    invisible(.Call(`_TiMEstamp_cxx_convert_maf_to_fasta`, maf_file, species_file, chrom_size_file, output_folder, reference_species, buffer_limit_mb))
}

cxx_fasta_gaps_to_bed <- function(fasta_files, bed_out, min_gap_inclusive = 10L) {
    invisible(.Call(`_TiMEstamp_cxx_fasta_gaps_to_bed`, fasta_files, bed_out, min_gap_inclusive))
}

cxx_merge_ranges <- function(chrom, start, end, strand, grp, tol) {
    .Call(`_TiMEstamp_cxx_merge_ranges`, chrom, start, end, strand, grp, tol)
}

